### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by olsonperrensen** [olsonperrensen/BizManager#1]
# Pending tasks of the Android Project
- [ ] How to use preferences to set layout and save it
- [ ] How to change the text color and style of app title bar
- [ ] Change of themes from the theme button implemented
- [ ] How to access the directory photos of your device (tip add an entry to the android manifest file and get a sample of how to get info from the content manager) 
- [ ] Research which image `recycleviewer` to use? Picasso or others?
- [ ] `existsUserTheme` always returns false! (fix it!)
- [ ] Change the hearts pictures on the Main Activity menu
- [ ] Implement Logic to change View Mode of the pictures - Change Layout of `RecyclerView` dynamically!
- [ ] Change Button text from Single to Grid after every click.
- [ ] Select various items from `recyclerview` to add to favorites with a press of the favorite button
- [ ] New to manage boolean of selection with click and long pressed on the figures (register id and set selection to enable to change visibility)

# Items that must be included in the project:
- [x] Different activities and use of intents
- [x] Different layouts for portrait and landscape mode
- [x] Different localization in at least two languages (English and Dutch)
- [x] Two or more user settings
- [x] `RecyclerView` use
- [x] Use of a Database
- [x] Internet usage
# Personal To-Do's
- [x] PO API
- [ ] Expand details liked employee
- [x] About page
- [ ] Update/Delete ROOM employees
